image: node

before_script:
  - yarn --frozen-lockfile install

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

pages:
  script:
    - yarn build && yarn export
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - master
